### PR TITLE
Count the HA nodes from the machines dump file, not agent.conf

### LINKED ISSUE #12: Using apiaddresses in agent.conf to count HA nodes is wrong
It doesn't work if the machines have more than one address, since they're both listed in the config.

Change it to use the machines.bson from the dump, looking for machines with model-uuid=controller-model and jobs includes 2 (state.JobManageModel).

### PR DESCRIPTION
**Pull request by babbageclunk**
## Description of change

We can't use the API address count in the agent.conf as the count of HA nodes - it gives the wrong result when machines can have more than one address. Replace it with reading the machines dump file and counting machines in the controller model that have the manage models job.

Fixes #12. 

## QA steps

* Bootstrap on AWS.
* Create a backup.
* Restore it - the restore shouldn't complain about an HA node count mismatch between the controller and backup.

### CODE REVIEW

File: backup/metadata.go [hunk 1]
```diff
@@ -137,38 +140,75 @@ func flatV0ToBackupMetadata(source flatMetadataV0, haNodes int) core.BackupMetad
...
+		}
+
+		buf.Reset()
 	}
-	agentConf, err := os.Open(matches[0])
+}
+
+const jobManageModel = 2
+
+func countHANodes(directory, modelUUID string) (int, error) {
```
Comment (howbazaar) [inline backup/metadata.go:178]: Can we prefer to count the controllerNodes collection? It will be more accurate going forwards as we want to remove jobs from machines.

However for older Jujus that don't have a controllerNodes collection, we will have to count the jobs.

Comment (babbageclunk) [reply backup/metadata.go:178]: Ok - I'll have a look how that's represented in the db docs and do that.

**Comment by babbageclunk** [comment]
$$merge$$
